### ISSUE TITLE
IOs Compatibility

### ISSUE THREAD

**Issue by salvov** [awe-media/awe.js#1]
Hi There,

I'm testing your Geo AR examples and it all works fine on an android device but not on iOS.
For what I now WebGL are now supported on iOS devices.

So in theory this should work on my iPhone but it get a fallback message still.

Is this something related to the library itself or is there some line of code on the  on the example that I need to deactivate/remove?

Cheers,
Salvo

**Comment by awe-media** [comment]
Hi @salvov - this definitely should work on iOS (try loading https://awe.media or https://demo1.awe.io).

The basic geo/gyro AR example has a bit of old code left in it from the old repos which and we'll be pushing updates to that later this week. This should fix any problems you might be seeing there.

I'll leave this issue open for now and then close it when we push these updates.

If you have any other questions please let us know.

**Comment by awe-media** [comment]
The examples in basic_ar/ have been updated and moved to basic/ and tested ok on iOS.
