### ISSUE TITLE
How can I load .fbx scene with animation?

### ISSUE THREAD

**Issue by m1gu** [awe-media/awe.js#11]
I try to load fbx scene but I think my code is wrong.
You have some example code for fbx animation?

Best regards,

Miguel Angel

**Comment by awe-media** [comment]
Hi @m1gu we don't currently support fbx loading - however we'll be releasing a range of new loaders/format support in the new year.

We'll leave this issue open until they are released.

**Comment by Dhamu143** [comment]
any update on this issue?

**Comment by jacksolutions** [comment]
we also want to load fbx file in AWE, is there any example available or any guide how to achieve it? @m1gu were you able to do it?

**Comment by binita12345** [comment]
any update on this issue?

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
