### ISSUE TITLE
How to add custom markers

### ISSUE THREAD

**Issue by b1o** [awe-media/awe.js#12]
How does one add a custom marker for detection? Every example I've seen uses the 64 marker, but how do i define my own marker pattern

**Comment by awe-media** [comment]
Hi @b1o - the version of JSARToolkit used is configured to automatically detect markers with an internal grid of 5x5 squares. The set of standard markers are available here:
 
  https://github.com/kig/JSARToolKit/tree/master/demos/markers

NOTE: These are all `.png` files but don't have the suffix on their filenames.

To add your own custom markers you need to dive deeper into the JSARToolkit code to encode your own pattern files then load them so they are tracked.

However, we'll be releasing a whole range of new tracking options in the new year that will allow you to add your own reference patterns.
