### ISSUE TITLE
.png texture not transparent

### ISSUE THREAD

**Issue by sebi-b** [awe-media/awe.js#13]
Hey there.

If I add a .png image as texture at the marker example, the png background is always white. Even if I set the transparent value.

Do you have any idea?

**Comment by awe-media** [comment]
Hi @sebi-b here's an example of the minimal `material` settings you need for a transparent projection with an image `texture` (in context). We've added in the `color` white as this makes the texture look brighter but this is not required.
```
awe.projections.add({
  id:'my_projection',
  geometry: { shape: 'plane', width:100, height:100 },
  material:{ type: 'phong', color: 0xFFFFFF, transparent:true },
  texture: { path: 'my_transparent_image.png' },
}, { poi_id: 'my_poi' });
```

We'll close this now as this definitely works - but if you have problems getting it working just paste an example of your code in a comment.
