### ISSUE TITLE
Track 3D position/projection. Supported?

### ISSUE THREAD

**Issue by devotionsolutions** [awe-media/awe.js#14]
Hello, I'm considering awe.js for a small augmented reality game/application. Instead of using a marker, I'd like to track a colored rectangle or a custom object (a very simple object like a jar)/an image, etc. Do we have something like that in awe.js? (a marker-less object detection)
I was taking a look at the location based AR video example (https://www.youtube.com/watch?v=OJHgBSRJNJY&feature=youtu.be) and those objects are keeping the 3D position. So, I wonder if it is possible to track the 3D position/projection of any of the detected objects and then reposition the assets based on it.
Thanks!

**Comment by awe-media** [comment]
Hi @blumersolutions that location based example uses the GPS on the mobile device to work out your position and then places the objects relative to that. You can use that right now.

We are releasing natural feature tracking (e.g. image based tracking) this year but have no fixed date for that at the moment.

We're also releasing some examples of depth based tracking (e.g. using depth sensors to scan 3D objects/spaces). But again we have no fixed date for that right now.
