### ISSUE TITLE
Add typings for typescript

### ISSUE THREAD

**Issue by shaneparsons** [awe-media/awe.js#15]
Typescript's fairly new to me so I don't have any examples, but I know typings make it a lot easier to integrate external code like this into a ts project.

**Comment by awe-media** [comment]
Hi @shaneparsons - if you'd like to make a pull request we'd be happy to integrate it.

**Comment by shaneparsons** [comment]
It's too unfamiliar a territory for me at this point in time, but I'll update this if that changes.

**Comment by awe-media** [comment]
No problems @shaneparsons - we're looking at lots of updates so we'll keep this in mind. Closing it for now but will review again soon. Shout if you have any other suggestions.
