### ISSUE TITLE
AR Marker compatibility with safari mobile IOS 

### ISSUE THREAD

**Issue by m1gu** [awe-media/awe.js#16]
Hi, I try to run a basic AR Marker demo on Safari with my Ipad, but in the screen nothing appear.

Regards,

**Comment by awe-media** [comment]
Hi @m1gu iOS doesn't support `getUserMedia()` (or WebRTC in general) so camera access is unavailable. 

If you're creating location based AR then you can fallback to using a 360° photo or video on iOS devices.

But at the moment no kind of computer vision is available on iOS on the web platform.

We're hoping Apple resolve this in their next Safari update.
