### ISSUE TITLE
Transparency with PNG

### ISSUE THREAD

**Issue by angenieux** [awe-media/awe.js#17]
Hi,
i'm trying to display a plane with "concept.png" texture (with alpha chanel = transparency)
The following code was OK with older repository Buildar. No more with awe-media.
Any idea ?
Thanks :)

awe.projections.add({ 
	id:'e', 
			          geometry:{ shape:'plane', width:252, height:100, widthSegments:10, heightSegments:10 },
				      texture: { path: 'concept.png' },					  
                      rotation:{ x:0, y:90, z:0 },
			          material:{ color:0xFFFFFF },
			        }, { poi_id: 'east' });

**Comment by awe-media** [comment]
Hi @angenieux - that's a nice easy one!

Just make sure you add `transparent:true` to your `material` block so it is transparent e.g.

```
awe.projections.add({
  id:'e',
  geometry:{ shape:'plane', width:252, height:100 },
  texture: { path: 'concept.png' },
  rotation:{ x:0, y:90, z:0 },
  material:{ color:0xFFFFFF, transparent:true },
}, { poi_id: 'east' });
```

**Comment by angenieux** [comment]
Thanks a lot to the team! Great Job.
Do you also have an example with TEXT display ?
I m looking for the mandatory parameters.
br

**Comment by awe-media** [comment]
Hi @angenieux checkout the example on the wiki at https://github.com/awe-media/awe.js/wiki/text-example

**Comment by angenieux** [comment]
Hello I've checked the example but without success.
I have converted a windows font .TTF into a .js with typeface.js and product a file "Arial_Regular.js".
"Arial_Regular.js" is located on the webserver at the same level as the HTML file 

Here my code:
 awe.projections.add({ 
			          id:'w', 
			          geometry : { font_url: 'Arial_Regular.js', parameters:{height:5, size:10}, shape:'text', text: "your path"},
			          texture: { path: 'pilogo.png' },					  
			           rotation:{ x:90, y:0, z:90},
			          material:{ type: 'phong', color:0xFFFFFF}
			        }, { poi_id: 'west' });

Any idea ?
