### ISSUE TITLE
I attempted the Stereo example and it failed

### ISSUE THREAD

**Issue by 6monkeyrs** [awe-media/awe.js#19]
its looking for this plugin, but I was not able to located with the download packages geo_ar.js

All other examples are working good for me.

**Comment by awe-media** [comment]
Hi @6monkeyrs thanks for reporting the issue. 

We've updated the index.html file with a link to the correct js file. See https://github.com/awe-media/awe.js/commit/616492591896a61bad2d9832a034288312861685 and this should fix the problem.

Please let us know if you find any other issues 8)
