### ISSUE TITLE
Add wiki docs on progress_callback

### ISSUE THREAD

**Issue by awe-media** [awe-media/awe.js#2]
In the meantime checkout the code.

**Comment by lucaszhu2zgf** [comment]
I found the way to create custom marker is kind of complicated...

**Comment by awe-media** [comment]
Hi @louiszhu2zgf - that's defined by the underlying ARToolkit framework. Plugins for other tracking solutions will be released here soon.

Also, this is not really related to `progress_callback` so we'll leave this issue open 8)

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
