### ISSUE TITLE
cubes seems to drift when running ar.html example on mobile and keeping the phone still.

### ISSUE THREAD

**Issue by Miojo** [awe-media/awe.js#20]
Is there a way to solve this problem? Is there a way to spawn a cube initially in the middle of the camera screen and make it so it doesnt drift? (maybe its a gps thing idk)

**Comment by awe-media** [comment]
Hi @Miojo - if you're not using gyro driven content then just comment out the reference to `awe.gyro.js` and this will remove this issue.

Please let us know if this doesn't fix your issue.

BTW: We're releasing an updated version of our awe.media platform in a few weeks that integrates the location based coordinate space with marker tracking etc. You might like to check that out then.

**Comment by Miojo** [comment]
I am using the gyro feature, the problem was that the cubes were drifting even when my phone was completely still. I tested with another phone and it worked flawlessly, the problem might be in my Motorolla moto X (XT1058) gyroscope.
Thanks for your help.
