### ISSUE TITLE
Is it possible to show a GIF with a transparent background in an AR scene??

### ISSUE THREAD

**Issue by Miojo** [awe-media/awe.js#21]
trying with 
geometry:{ shape: 'plane', width:100, height:100 },
material:{ type: 'phong', color: 0xFFFFFF, transparent:true },
texture: { path: 'mygif.gif' },

says that gif format is not valid (and also puts a black background).

Is it possible to do it with a transparent mp4 instead of a gif?

**Comment by awe-media** [comment]
I'd recommend trying a png if you want transparent backgrounds as that works reliably.

You can use .mp4 files as textures easily (just change the path name), but the transparency isn't automatically handled as the video formats don't encode this automatically and it requires additional texture processing. We're also working on some animation handlers that will enable animated gifs for textures, but there's no scheduled release date for this.
