### ISSUE TITLE
Spawning an object in front of the camera on mobile

### ISSUE THREAD

**Issue by Miojo** [awe-media/awe.js#22]
Using the position (0,0,-200) I can spawn objects in front of the camera on the browser, but when switching to mobile that is not always valid since the camera will not always be facing the same way.
is there a way to get the vector that the camera is facing to or something like that? Any way to spawn an object right in front of the current camera position?
Sorry for asking a lot of questions hehe... the documentation is short

**Comment by awe-media** [comment]
Hi @Miojo there's a few ways you can do this. Getting the `awe.pov()` you can get it's orientation from it's `rotation` object. From this you can project a vector and pick a point any distance in front of the camera. You can also add objects as children of the pov so they are always stuck to the front of the camera - but that may be different from what you're looking for. If you can provide a bit more info on exactly what you want we can provide some simple code examples that should help.
