### ISSUE TITLE
where I can find the COMPLETE documents of awe.js

### ISSUE THREAD

**Issue by LittleXiaosi** [awe-media/awe.js#23]
I saw the example of awe.js，there is some code like `window.awe.init``awe.util.require`` capabilities: ['gum', 'webgl'],
    files: [
    ['#link(../lib/awe-standard-dependencies.js)', '#link(../lib/awe-standard.js)'],
     '#link(../lib/awe-jsartoolkit-dependencies.js)',
     '#link(../lib/awe.marker_ar.js)'
 ],`
but I never find the doc of those function in wiki..

**Comment by awe-media** [comment]
Hi @LittleXiaosi the wiki and the source code and examples contain all the documentation that's currently published. If you have any specific questions we're happy to help and the working examples should provide you everything you need to get started.

For the `awe.util.require` function, this just provides you with a way to load specific files in a specific order as many parts of web based Mixed Reality have order based dependencies.

See the simple [vr.html](https://github.com/awe-media/awe.js/blob/master/examples/basic/vr.html) file in the [examples/](https://github.com/awe-media/awe.js/blob/master/examples/) directory. Each of the library files loaded had comments beside them - I've added some more comments inline here which should hopefully help.
```
  window.addEventListener('load', function() { // setup your script to only run once the page has loaded
    window.awe.init({ // initialize awe after page loads
      device_type: awe.AUTO_DETECT_DEVICE_TYPE, // automatically detect the device type
      settings: { ... }// populate some default settings
      ready: function() { // this function is run once awe initialisation is complete and awe is ready
        var d = '?_='+Date.now(); // a basic timestamp for cache busting
        awe.util.require([ // a utility that lets you "require" (e.g. load) files and in a specific order
          {
            capabilities: ['webgl'], // only browsers with these capabilities will load the files and success handler below - see `awe.capabilities.list()` for a complete set
            files: [ 
              [ '../../js/awe-standard-dependencies.js'+d, '../../js/awe-standard.js'+d ], // load these core dependencies first and together in this order 
              ['../../js/plugins/StereoEffect.js'+d, '../../js/plugins/VREffect.js'+d], // then load the dependencies for render effects together in this order
              '../../js/plugins/awe.rendering_effects.js'+d, // then load the actual rendering effects plugin
              '../../js/plugins/awe-standard-object_clicked_or_focused.js'+d, // then load the object click/tap handling plugin
              'awe.gyro.js'+d, // then load the basic gyro handling plugin
              'awe.mouse.js'+d, // then load the basic mouse handling plugin
            ],
            success: function() { 
              ... // your code goes here - it will be run if everything above succeeded
            },
          },
          ... // other capability based require calls can go here for other device classes
        }
      }); // awe init code ends
    }); // onload code ends
```

**Comment by Dhamu143** [comment]
how can implement awe.js is in mobile aaplication? i am using ionic framework

**Comment by awe-media** [comment]
Hi @Dhamu143 you should be able to simply load an `awe.js` app inside your app's WebView (or equivalent). As long as that web container supports the required capabilities then it will run. But support for any specific framework (e.g. ionic) is not something we can provide here.

**Comment by vaishali-Bhakhar** [comment]
ready: function() { // this function is run once awe initialisation is complete and awe is ready
        var d = '?_='+Date.now(); // a basic timestamp for cache busting
        awe.util.require([ // a utility that lets you "require" (e.g. load) files and in a specific order
          

Here we are using ready function that ll load only once when app ll be loaded
but i want to run my code every time when i enter the page.

i am using ionic
so,for example,
i have put my code in controller1
now if for 1st time i ll go to controller1 it ll work fine,it ll go inside ready() and run code
but if i go to some other page i.e. in controller2, then agian if i ll go to controller1 it ll never go to ready() as ready() ll execute only once when app ll be loaded.

so,is there any solution?

**Comment by awe-media** [comment]
Just use the standard window events here.
```
window.removeEventListener('window_visible', YOUR_FUNCTION_HERE);
```
