### ISSUE TITLE
Moving and scaling 3D object

### ISSUE THREAD

**Issue by vladotesanovic** [awe-media/awe.js#24]
Hey there,

Tnx for great library, keep going :+1: 

I have one question: Did you published example anywere with this transformation / moving like on this demo?
https://youtu.be/LxVRBxC-SHY?t=20s

**Comment by awe-media** [comment]
Hi @vladotesanovic you can simply move and scale any of your objects by using the `awe.js` api.  You can use this with your own standalone `awe.js` project based on this github repos, or just try this on a free [awe.media](https://try.awe.media) app if you like too. Just open your free [awe.media](https://try.awe.media) app or your standalone project in your browser and make sure your scene already contains some pois and projections. Then open the javascript console and try out this type of code:
```
// get the projection you want to rotate or scale - this is the 3D object that user's actually see
// here we're just grabbing the first in the list [0]
var my_projection = awe.projections.list()[0];

// get the poi you want to move - this provides the origin for your object
var my_poi = my_projection.parent();

// output the poi id
console.log("poi:"+my_poi.id)

// output the projection id
console.log("projection:"+my_projection.id)
```

Now you can use this poi and projection to move and animate your object.
```
// animate the object's poi to move over 5 seconds
awe.pois.update({
  data:{
    position:{ z:-10000 },
    animation: {
      duration: 5, // animate over 5 seconds
      persist: 1, // stay at the end value e.g. don't reset afterwards
    }
  },
  where: { id:my_poi.id }
});

// rotate the object's projection around it's y axis over 5 seconds
awe.projections.update({
  data:{
    rotation:{ y:360 },
    animation: {
      duration: 1, // animate over 1 seconds
      persist: 0, // reset back to the original values after animation is over
      repeat: 5, // do this 5 times for a total of 5 seconds e.g. repeat * duration
    }
  },
  where: { id:my_projection.id }
});
```

Of course if you have the objects already (as in the code above then you can use the simpler version of the api for updates too.
```
my_poi.update({
  position:{ z:-10000 },
  animation: {
    duration: 5, // animate over 5 seconds
    persist: 1, // stay at the end value e.g. don't reset afterwards
  }
});

my_projection.update({
  rotation:{ y:360 },
  animation: {
    duration: 1, // animate over 1 seconds
    persist: 0, // reset back to the original values after animation is over
    repeat: 5, // do this 5 times for a total of 5 seconds e.g. repeat * duration
  }
});
```

For more information on tweening see the [tweening examples page](https://github.com/awe-media/awe.js/wiki/tweening-example) on the wiki.

Hope that helps.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
