### ISSUE TITLE
Outdated docs / which files to import?

### ISSUE THREAD

**Issue by shaneparsons** [awe-media/awe.js#26]
Since there doesn't seem to be a file named `awe.js` (as stated in the readme), I'm just wondering which js file/s to import?

`examples/ar.html` is importing `awe-v8.js` and `awe-loader.js`, but there is no mention of this in the readme so I'm unsure. Also, if those are the only files needed, what are the other 2 for?

**Comment by shaneparsons** [comment]
I was able to get it working, but the docs should still be updated.

**Comment by awe-media** [comment]
Hi @shaneparsons - fair point about the difference between the two. We'll look at updating them in the next release. But the key point is that the docs on the repos home page just show the general setup. Then the examples files show working examples of everything you need to get a scene working - so just start with one of them and go from there.
