### ISSUE TITLE
Render image without 3D object

### ISSUE THREAD

**Issue by shaneparsons** [awe-media/awe.js#27]
I'm just wondering if there's a way to simply add an image (ideally an svg image) on the screen without having to apply it as a texture to a 3D object?

I have no need for 3D objects or orientation / rotation, I just want a flat, svg, marker placed in front of a chosen location. Is that possible? or is my only option to add a png to a plane object?

**Comment by awe-media** [comment]
Hi @shaneparsons - it's not 100% clear what you mean from your comment above. 

If you just want to add a persistent flat overlay image you can simply add an html overlay on top of your awe scene. The whole awe.media UI is implemented that way. 

But when you say "in front of a chosen location" then you are actually implying a spatial component, which by definition includes position and rotation. This is then something best dealt with inside the awe scene - and that's exactly what 3D objects with textures delivers. 

BTW: The file format of these textures is defined by WebGL and your browser's graphics layer implementation and is not just limited to .png.

If you can provide a bit more detail about what you mean then we'll try to help you further.

**Comment by shaneparsons** [comment]
Basically, I just want to add a marker (similar to a pin on a map) to areas of interest as a person walks through town (e.g if somebody points their phone towards the beerstore, I'd like to show a pin in front of it based on its coordinates).

I just want the pin to be a flat image, that always faces the user, and I just figured if there's a way to do it with a flat image, rather than applying a texture to a plane object, it wouldn't use as many resources to render.

Let me know if it's still not clear enough.

**Comment by awe-media** [comment]
Hey @shaneparsons - based on your description you're really describing some form of 3D geometry or scene.

- locations (user and place)
- points their phone towards (e.g. a direction vector)
- have the user see a pin in front of the place

The easiest and most performant way to manage 3D geometry on the web is using WebGL as it is optimised to use GPUs and provides all the required 3D math in a highly optimised format.

So I'd recommend just using a standard awe scene and using the simple API calls as discussed in your other ticket.

If you want the object to always face the user then you can utilise the `lookAt()` function. Just walk through the array of your pois. And tell each of them to look at the camera.
```
awe.pois.list().forEach(function(poi) {
  poi.get_mesh().lookAt(awe.pov().position);
});
```

If you combine this with the other ticket and the files in the examples repos it should definitely give you everything you need to get started. But please let us know if you have any other questions.
