### ISSUE TITLE
AR doesn't work on iPhone with iOS 10.3

### ISSUE THREAD

**Issue by pmikla14** [awe-media/awe.js#28]
Hi!

I put your examples on our server today to test awe.js a little bit, but I recognized that it neither works on my Mac, nor on my iPhone ("This demo currently requires a standards compliant mobile browser."). 

Android is working fine. Is this a known issue? Or am I doing something wrong?

Thanks, 
Philipp

**Comment by awe-media** [comment]
Hi @pmikla14 - Apple have not yet adopted the WebRTC based `getUserMedia()` API which provides access to the camera. We're hoping they'll announce that in the next update to iOS/Safari.

The `capabilities` section in the `require()` call (see vr.html vs ar.html the examples/basic directory) allows you to filter based on the browser's capabilities (e.g. `gum`). 

Also checkout https://awe.media to see a good working version of how you can automatically fallback to 360° backgrounds for spatial AR for iOS.
