### ISSUE TITLE
Project is alive?

### ISSUE THREAD

**Issue by nikkwong** [awe-media/awe.js#29]
Hi,

Is this project still alive? There hasn't been a commit for months and the website is down.

Thanks.

**Comment by awe-media** [comment]
Hi @nikkwong - yes the project is clearly alive. Checkout the issues answered recently and the last commit was only 2 months ago - I'd bet the majority of github is longer than that. And our site is definitely up.

**Comment by nikkwong** [comment]
No need to get defensive. I was just asking :-) it was down for a bit earlier. 

Project looks good—I can't seem to get any video feed on iOS in my awe app though. Is that a bug? 

Thanks! Looking forward to using.

**Comment by robman** [comment]
Hey @nikkwong didn't mean to come across that way 8)

Yeah Apple have not yet adopted the WebRTC based getUserMedia() API which provides access to the camera. We're hoping they'll announce that in the next update to iOS/Safari.

The capabilities section in the require() call (see vr.html vs ar.html the examples/basic directory) allows you to filter based on the browser's capabilities (e.g. gum).

Also checkout https://awe.media to see a good working version of how you can automatically fallback to 360° backgrounds for spatial AR for iOS.

Shout if you have any other questions.

**Comment by nikkwong** [comment]
Very helpful thx so much!
