### ISSUE TITLE
Want to rotate an object with touch and drag

### ISSUE THREAD

**Issue by bjornaer** [awe-media/awe.js#3]
I am trying to make an object rotate with touch start and touch move, but I have many objects loaded, and only one generic eventListener (building my stuff off the example from basic). I do not know how to tell it that if someone touches an object and moves it's finger, the object should rotate as the finger drags it.
(my concern is that all of the objects will move when you try to rotate only one.)
[and another problem is how do I ask that.]

Thank you for your help!

**Comment by awe-media** [comment]
Hi @Draska - thanks for your question. This is more of a "request for a tutorial" than an issue 8)

I'd checkout the code in one of the examples that handle clicks - see:
https://github.com/awe-media/awe.js/blob/master/examples/basic/vr.html#L84

You could setup a similar listener:

```
window.addEventListener('object_clicked', function(e) {  ... }
```

Inside this block you can then set a variable that tracks the currently selected object.

Then setup some touch/drag events that get the `x` value of the touch/drag and use that to rotate the object with a simple `awe.pois.update({ data:{ rotation:{ y:new_rotation_value }, where:{ id:currently_selected_poi_id } })` if the selected object variable is set.

Then in an onmouseup/touchend handler you can clear that selected object variable.

That should give you everything you need.

If you'd like to contribute some code like that to the wiki as an example once you're done that would be great.

We'll close this issue now and please shout out if you have any other questions.
