### ISSUE TITLE
Cannot get user media on iOS

### ISSUE THREAD

**Issue by gpanneti** [awe-media/awe.js#30]
I tried the example of geoAR. It works perfectly on Android (need to serve it over HTTPS), but nothing on iOS.

When I remove the dependecy to  "gum", it works well.

Does someone knows how to fix this ?

**Comment by awe-media** [comment]
Hi @gpanneti - iOS doesn't currently support gUM - see issue #28 

So in this case - removing the "gum" dependency is the right solution if you also want to support iOS.
