### ISSUE TITLE
Use awe.js on ionic/cordova app

### ISSUE THREAD

**Issue by jacksolutions** [awe-media/awe.js#32]
As this awe.js uses getUSERMEDIA which is only supported on android and not in ios, we are here making a POI location based mobile app where you display POI around your current lat and long on camera feed and that too in 3d.

i didnt get any free SDK for this thus i am trying to use combination of ezar and awe.js.

so idea is  i want to disable getusermedia of awe.js for camera feed and instead use ezar camera feed so that it works on both ios and android and then rest of the logic of awe.js to render POI on 3d view.. is that possible? if yes how can i achieve it.

Please help as we are stuck on it and i will really really really appreciate it.

**Comment by awe-media** [comment]
Hi @jacksolutions that's a nice easy to answer question.

If you look in the [examples/ar.html](https://github.com/awe-media/awe.js/blob/master/examples/basic/ar.html) file you'll see that the only code that really turns on the camera is this line: 
```
awe.settings.update({data:{value: 'ar'}
```

But if you simply start with the [examples/vr.html](https://github.com/awe-media/awe.js/blob/master/examples/basic/vr.html) file and go from there without that line you should be fine. Just make sure the background on your container is transparent and then you can use any camera/video layers you want beneath that.

**Comment by guillemonzo** [comment]
@jacksolutions Hi! I'm also trying to develop an Ionic2 app with ezAR and awe.js. I'm stuck in how to import awe.js in the app. Can you please share the required code to initialize awe.js in a Ionic2 component? Thank you so much in advance.
