### ISSUE TITLE
Cannot load .obj file

### ISSUE THREAD

**Issue by turnerniles** [awe-media/awe.js#33]
Similar to https://github.com/awe-media/awe.js/issues/10

I cannot load a .obj file into awe.js

```
awe.projections.add({ 
  id: 'bacon', 
  geometry: {
    path: 'https://raw.githubusercontent.com/turnerniles/awe-kawaii-breakfast/master/public/basic/models/CuteBacon.obj'
  },
  position: { x: 0, y: 0, z: 0 },
  rotation: { x: 0, y: 180, z: 0 },
}, { poi_id: 'bacon' });
```

I get the error:
Uncaught Error: Unexpected line: mtllib	CuteBacon.mtl
    at THREE.OBJLoader.parse (awe-standard-dependencies.js?_=1494708458859:1316)
    at awe-standard-dependencies.js?_=1494708458859:1001
    at XMLHttpRequest.<anonymous> (awe-standard-dependencies.js?_=1494708458859:387)

The prior issue recommends loading it into the web platform. But that doesn't work either. Is there a specific file type I need to use or some type of cleaning I need to perform on the file?

**Comment by awe-media** [comment]
Hi @turnerniles just add a reference to the `.mtl` file referenced in your `.obj` file as a parallel to the `geometry` key using the `material` key. e.g.
```
awe.projections.add({ 
  id: 'bacon', 
  geometry: {
    path: 'https://raw.githubusercontent.com/turnerniles/awe-kawaii-breakfast/master/public/basic/models/CuteBacon.obj'
  },
  material:{
    path: 'https://raw.githubusercontent.com/turnerniles/awe-kawaii-breakfast/master/public/basic/models/CuteBacon.mtl'
  },
  position: { x: 0, y: 0, z: 0 },
  rotation: { x: 0, y: 180, z: 0 },
}, { poi_id: 'bacon' });
```

That should fix it up.
