### ISSUE TITLE
Newer version of three.js?

### ISSUE THREAD

**Issue by ezartech** [awe-media/awe.js#36]
Thanks for the great work.
Are there any plans to upgrade to a newer version of three.js? 
If yes, can you share a timeframe when it the update is planned?

**Comment by awe-media** [comment]
Hi @ezartech yes we have a release coming up soon. However, we can't guarantee a timeframe for this as our dev team is busy with the new https://awe.media platform release and adding new computer vision features too.

We were hoping to have completed this by now, but realistically this is another 4-6 weeks away.

Thanks for your feedback and I hope this help.
