### ISSUE TITLE
No camera view on android with cordova. "Browser doesn't support VR "

### ISSUE THREAD

**Issue by mladenp** [awe-media/awe.js#4]
I tried to use awe geolocation example and managed to setup everything correctly and see 3D models but no camera view. 
I am using Cordova with ionic on Android. I tried adding crosswalk but still nothing. It gives me warning: "Your browser doesn't support VR" i am using Android 6, its WebView should support camera view as far as i know.

**Comment by awe-media** [comment]
Hi @mladenp thanks for raising this issue.

The "Your browser doesn't support VR" issue is a separate warning and not related to camera access through the `getUserMedia()` api.

Have you tried opening that awe page directly in a browser (e.g. Chrome or Firefox) on that same Android device? This should confirm if the basic structure of your app is working.

Happy to help you debug a bit further from there...

**Comment by mladenp** [comment]
My problem was something else, can't remember exactly what was it.
I made it work but i still got the same warning message, so something is wrong with the error messages but the library works.

**Comment by awe-media** [comment]
OK thanks for the update - I'll close this ticket then 8)

**Comment by jacksolutions** [comment]
@mladenp can you please provide a sample code of how you achieved it with ionic and cordova, we are also developing a similar app that we need to show POI on mobile camera using cordova.

you help will be highly appreciated.

Thanks

**Comment by mladenp** [comment]
@jacksolutions that was some prototype i was building long time ago so i don't have the code.
But it definitely works fine, especially with new Ionic 2.
You can also checkout Aframe.io
