### ISSUE TITLE
How to make video mesh play?

### ISSUE THREAD

**Issue by HumberSean** [awe-media/awe.js#42]
Hello, I can create a mesh with video, but Android keeps the video from playing by default.  How can I access the video and have it play on click?  I see there is a play() method in the wiki, but not how (or where) to access the mesh.

**Comment by awe-media** [comment]
Hi @HumberSean you can access the video texture and play/pause it using `play_video_texture()` and `pause_video_texture()`. Checkout the documentation in https://github.com/awe-media/awe.js/wiki/awe-objects#awe_mesh_object

Shout if you have any other questions about this.

**Comment by awe-media** [comment]
Ah one other issue that's relevant - on mobile devices (e.g. Android and iOS) the browsers often require a user action to play any media. So any of your play() calls need to be called from within a user action (e.g. a click event).

**Comment by HumberSean** [comment]
Thank you for your response - and for noting the Android "gotcha".  The element missing from the API is an example of how to put the pieces together.  I can see the awe.pois etc for getters, and the methods to call (thank you for the stop method!), but not how to get the mesh and call play on the video texture.
I have tried:
var mypoi = awe.pois.view("mypoiID");
mypoi.play_video_texture();
...and...
var myprojection = awe.projections.view("myprojectionID");
myprojection .play_video_texture();
...and...
awe.textures.play_video_texture();
but it isn't working.  I know the click event is working because I have a console message that shows up.
This is an amazingly exciting library with a tremendous amount of thought behind it.  We just need a few examples in the API (without having to dig through the examples folder) to connect the dots.
I will be happy to share my working example once completed, as I know there are numerous people looking for this solution.
Many thanks again for your response and support!
