### ISSUE TITLE
Adding custom images as a marker image

### ISSUE THREAD

**Issue by krishnabharadia** [awe-media/awe.js#44]
Recently, I have seen a closed issue where the awe team replied saying that they will add support for scanning of custom markers. Is it available now ?
Basically, i want to scan a image and get overlay image displayed on it. Is this possible using awe.js?

**Comment by awe-media** [comment]
Hi @krishnabharadia - this is possible but requires you to do custom coding. What we're focused on now is providing true Natural Feature Tracking and are planning on releasing this as part of our awe.media platform in late September or early October. This allows you to use standard images like photo, product packaging, posters, book covers, etc. without the need for the ARTookit style black borders. This also works on both Android and iOS (requires iOS11+). Stay tuned to our twitter account and we'll make more announcements there when it's ready.

**Comment by krishnabharadia** [comment]
Ok... Thank You..
