### ISSUE TITLE
How can I load .gif instead of.png in texture in awe.js 

### ISSUE THREAD

**Issue by binita12345** [awe-media/awe.js#45]
awe.projections.add({
                                id: zoneUser.email + '->' + Math.random(),
                                // geometry: { shape: 'cube', x:50, y:50, z:50 },
                                geometry: {
                                    shape: 'plane',
                                    height: 10,
                                    width: 20
                                },
                                position: {
                                    x: 0,
                                    y: 0,
                                    z: 0
                                },
                                rotation: getRotation($scope.poiBarrings[zoneUser.fullname]),
                                material: {
                                    type: 'phong',
                                    color: 0xFFFFFF
                                },
                                texture: {
                                    path: 'img/SB-Butterfly.gif'
                                 },
                            }, {
                                poi_id: zoneUser.fullname
                            });

Please give me any solution as soon as possible.

**Comment by awe-media** [comment]
Hi @binita12345 .gif should load ok...but animated gif's are not currently supported. However, if you convert your .gif to a small .mp4 or similar format movie then this should work fine.

**Comment by binita12345** [comment]
I have converted gif in .mp4 and used it in texture, 

texture: {
path: 'img/SB-butterfly.mp4'
},

it is working, but i am not getting expected result, it works as a downloading video, means where i want animated gif there i getting video as downloading on full scene.
