### ISSUE TITLE
iOS 11 - Camera input is rendered black

### ISSUE THREAD

**Issue by daryl-r** [awe-media/awe.js#47]
I tried out the basic AR example https://github.com/awe-media/awe.js/tree/master/examples/basic on iOS 11. The camera access prompt shows up as expected, but instead of displaying the camera input stream, it shows a black screen instead.

![image-1](https://user-images.githubusercontent.com/30885684/29199736-ec146c0e-7e81-11e7-97a0-d41e7f323012.jpg)

**Comment by awe-media** [comment]
Hi @daryl-r we have a commit that will add support for iOS11's gUM implementation over the next couple of weeks. There's a few issues (including the black screen) that we've fixed and the good news is that it works really well.

We'll leave this issue open and will add a comment here when we push this update.

**Comment by rkleijn** [comment]
Hi @awe-media do you have any update on this issue by any chance or could you point me to the commit so that i can test it? 
Support is greatly appreciated.

**Comment by daryl-r** [comment]
Seems pretty quiet here recently. I managed to get it working by making a hotfix for the new gUM implementation. Feel free to test this out: https://github.com/awe-media/awe.js/pull/62

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
