### ISSUE TITLE
Change text of an object

### ISSUE THREAD

**Issue by 1260811** [awe-media/awe.js#48]
Hi, I'm using a text object and I want to change the word from one to two like it is was counting, it´s possible? I tried using `awe.projection.update()` function but it doesn't work.

**Comment by awe-media** [comment]
Hi @1260811 we'll add a feature request to make this work with `update()` in an upcoming release. But in the meantime you can do this directly using code like this.

```
var projection_child = awe.projections.view('s').get_mesh().children[0];
var projection_params = projection_child.geometry.parameters.parameters;
projection_child.geometry = new THREE.TextGeometry( "YOUR NEW TEXT HERE", projection_params );
awe.scene_needs_rendering = 1;
```

We'll leave this issue open in case anyone else needs this workaround in the meantime.

**Comment by 1260811** [comment]
does it work using a marker recognition?

**Comment by awe-media** [comment]
This is a separate question, but just add a listener for the 'ar_tracking_marker' event that is thrown when the tracking runs - see the source code here https://github.com/awe-media/awe.js/blob/master/examples/marker_ar/awe.marker_ar.js#L416

Inside your listener you can add the code shown above to create what you want.

**Comment by 1260811** [comment]
Thank you, but I'm begginer and I don't know where I must add it, could you write a example?

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
