### ISSUE TITLE
How to create an custom marker ?

### ISSUE THREAD

**Issue by RatzSumit** [awe-media/awe.js#49]
We tried to use below mention steps, but unfortunately doesn't work. anyone can help with this ?
                Binding a POI to a jsartoolkit marker is easy
                - First add the awe-jsartoolkit-dependencies.js plugin (see above)
                - Then select a marker image you'd like to use
                - Then add the matching number as a suffix for your POI id (e.g. _64)
                NOTE: See 64.png in this directory or https://github.com/kig/JSARToolKit/blob/master/demos/markers
                This automatically binds your POI to that marker id - easy!

**Comment by awe-media** [comment]
The version of JSARToolkit used is configured to automatically detect markers with an internal grid of 5x5 squares. The set of standard markers are available here:

https://github.com/kig/JSARToolKit/tree/master/demos/markers

NOTE: These are all .png files but don't have the suffix on their filenames.

If you're having trouble with getting these working then please add a comment here with a sample of your code and we can help you with that.

If you want to add your own custom markers then you need to dive deeper into the JSARToolkit code to encode your own pattern files then load them so they are tracked.

What we're focused on now is providing true Natural Feature Tracking and are planning on releasing this as part of our awe.media platform in late September or early October. This allows you to use standard images like photo, product packaging, posters, book covers, etc. without the need for the ARTookit style black borders. This also works on both Android and iOS (requires iOS11+). Stay tuned to our twitter account and we'll make more announcements there when it's ready.
