### ISSUE TITLE
Problem with applying matrix transform to pois

### ISSUE THREAD

**Issue by mlison** [awe-media/awe.js#5]
I'm trying to apply matrix transformation from ```ar_tracking_marker``` event to another projection / poi, but to no effect. Also, adding multiple objects to a marker poi doesn't seem to be supported.

I've got roughly this:

```js
awe.pois.add({
  id:'masterPoi',
  position: { x:0, y:0, z:0 },
  visible: false
});

awe.pois.add({
  id:'jsartoolkit_marker_64',
  position: { x:0, y:0, z:0 },
  visible: false
});
```

Then I add one projection to the marker poi, and another projection to masterPoi. 
From the tracking event, I'm doing the following:

```js
if (marker) {
  awe.pois.update({
    data: {
      visible: true,
      matrix: marker.transform,
    },
    where: { id: 'masterPoi' }
  });
}
else {
  awe.pois.update({
    data: {
      visible: false
    },
    where: { id: 'masterPoi' }
  });
}
```

I've tried updating the projections directly with the same transform, but that doesn't work either.

I've also tried creating nested projections in the marker in hopes that it would update automatically according to the marker, but they don't seem to work with marker pois.

Is there anything obviously wrong with what I'm trying to do here?

**Comment by awe-media** [comment]
Hi @mlison in the new repos you don't need to write any code to bind pois to jsartoolkit markers which will hide/show automatically. See this example here:

https://github.com/awe-media/awe.js/blob/master/examples/marker_ar/index.html

Which includes this comment and code:
```
              /*
                Binding a POI to a jsartoolkit marker is easy
                - First add the awe-jsartoolkit-dependencies.js plugin (see above)
                - Then select a marker image you'd like to use
                - Then add the matching number as a suffix for your POI id (e.g. _64)
                NOTE: See 64.png in this directory or https://github.com/kig/JSARToolKit/blob/master/demos/markers
                This automatically binds your POI to that marker id - easy!
              */
              awe.pois.add({ id:'jsartoolkit_marker_64', position: { x:0, y:0, z:0 }, visible: false });
              awe.projections.add({
                id:'marker_projection',
                geometry: { shape: 'cube', x:50, y:50, z:50 },
                position: { x:0, y:0, z:0 },
                rotation: { x:0, y:0, z:180 },
                material:{ type: 'phong', color: 0xFFFFFF },
                texture: { path: 'awe_orange_square.png' },
                visible: false,
              }, { poi_id: 'jsartoolkit_marker_64' });
```

If you want to see how this plugin is handling matrix updates you can see these lines inside the awe.marker_ar.js plugin:
```
              mesh = poi.get_mesh();
              mesh.matrixAutoUpdate = false;
              mesh.matrix.setFromArray(Object.asCopy(marker_transform_matrix));
              mesh.matrixWorldNeedsUpdate = true;
```

We'll close this now, but please re-open it if you have any other questions about this.

BTW: Nested projections definitely work. See the example docs on the wiki.

https://github.com/awe-media/awe.js/wiki/nested-projections-example

Here's an example from that page - notice the second object param that includes `object_type` and `object_id`.
```
awe.projections.add({ 
  id: 'projection_2', 
  geometry: {
    shape:'octahedron',
    radius: 20
  },
  material:{ 
    type: 'phong',
    color: 0x0fc430,
  },
  position: { x: 0, y: 50, z: 0 }
}, { parent: { object_type: 'projection', object_id: 'projection_1' } });
```

**Comment by mlison** [comment]
Sorry perhaps I wasn't exact, in essence what I'm trying to do is bind multiple pois to one marker (or alternatively, apply the matrix transform from the tracking event to another poi) - is something like that possible?
