### ISSUE TITLE
Change the rotation of an object based on the position of the camera using a marker

### ISSUE THREAD

**Issue by 1260811** [awe-media/awe.js#52]
Hello, I want to display a text object but  I wish to see it always like I was seeing it from the front. I want to see this object only when  appear a special marker, too

**Comment by awe-media** [comment]
You can project a vector from the `pov` and get the world position of that, then move the object to that location on each tick. But a simpler way is probably just to create an html overlay and place HTML text with your numbers in the middle of the viewport.

Then you can use the `ar_tracking_marker` event as described here (https://github.com/awe-media/awe.js/issues/48#issuecomment-322307528) to show/hide this overlay.
