### ISSUE TITLE
how to unregister click event

### ISSUE THREAD

**Issue by Dhamu143** [awe-media/awe.js#58]
hello ,
as I load AR view window.addEventListener('object_clicked') gets registered. if i change view and then again come into the AR view this click event gets registered multiple time. so as I click on object it gets clicked more than one time(time that event is registered)

so how to unregistered that object_clicked event ?

here is the code to registered object clicked. so do i just need to remove event listener or i have to deal with this other objects also.? 
var click_plugin = awe.plugins.view('object_clicked');
                if (click_plugin) {
                    click_plugin.register();
                    click_plugin.enable();
                }
                var gyro_plugin = awe.plugins.view('gyro');
                if (gyro_plugin) {
                    gyro_plugin.enable();
                }
                var mouse_plugin = awe.plugins.view('mouse');
                if (mouse_plugin) {
                    mouse_plugin.enable();
                }
                var render_effects_plugin = awe.plugins.view('render_effects');
                if (render_effects_plugin) {
                    render_effects_plugin.enable();
                }
                window.addEventListener('object_clicked', function(e) {});

please explain in brief

**Comment by Dhamu143** [comment]
is there any update on this issue?

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
