### ISSUE TITLE
Why object is going on beside of its actual position when an object is clicked/tapped?

### ISSUE THREAD

**Issue by binita12345** [awe-media/awe.js#59]
when i put alert or get any data or call any function with get parameter in object_clicked event handler, object is going away from its actual position. objects should be stay on its current or actual or same position.  same problem is in awe demo also. and this issue is getting in ios only, it is working fine in android.

    window.addEventListener('object_clicked', function (e) {
                                alert("height clicked");
                                // alert('hiii...'+e.detail.projection_id);
                                var p = awe.projections.view(e.detail.projection_id);
                                p.play_video_texture();
                                // alert('p...' +p);
                                awe.projections.update({ // rotate clicked object by 180 degrees around x and y axes over 10 seconds
                                    data: {
                                        animation: {
                                            duration: 10,
                                        },
                                        rotation: {
                                            y: p.rotation.y + 180,
                                            x: p.rotation.x + 180
                                        }
                                    },
                                    where: {
                                        id: e.detail.projection_id
                                    }
                                });
                                
                            }, false);

what can i do to solve this issue?
please suggest me or give me some solutions asap.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
