### ISSUE TITLE
Destroy awe

### ISSUE THREAD

**Issue by andredewaard** [awe-media/awe.js#6]
Is it possible to destroy or delete awe?
I work with dynamic javascript routes to show pages. When i go to my AR page i initials Awe. When i go to a different page i want to delete the active awe so it won't throw errors because the dom elements doesn't exists anymore.
Getting this error now:
```
ReferenceError: FLARException is not defined
    at c.detectMarkerLite (http://localhost:8080/static/libraries/awe/plugins/awe-jsartoolkit-dependencies.js:11191:17)
    at handler (http://localhost:8080/static/libraries/awe/plugins/awe.marker_ar.js?_=1479532201377:357:37)
    at http://localhost:8080/static/libraries/awe/awe-standard.js?_=1479532201377:4139:20
```

**Comment by awe-media** [comment]
Hi @andre-dw - you can undefine awe if you like but you should disable all plugins before that.

It looks like you're just getting errors from the awe.marker_ar plugin so you can try calling this to disable it without needing to remove the whole awe object.

`awe.plugins.view('jsartoolkit').disable();`

Hope that helps.
