### ISSUE TITLE
how can i shake object from center on device?

### ISSUE THREAD

**Issue by binita12345** [awe-media/awe.js#60]
I am using **"cordova plugin add cordova-plugin-shake"** plugin to shake object in AR view in my app, but i getting issue in ios it's working fine in android.
my issue is that when i shake on particular one object  it gets clicked on another one besides of that one.

what should i do to solve this issue in ios.

**Comment by binita12345** [comment]
I am using **"cordova plugin add cordova-plugin-shake"** plugin to fulfill shake functionality in my app, but i getting issue in ios it's working fine in android.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
