### ISSUE TITLE
object is appearing on another angle

### ISSUE THREAD

**Issue by binita12345** [awe-media/awe.js#61]
why object is display on another angle using latitude, longitude rather than actual angle?
For example: My object polar angle is 70 and object is showing on angle 130.

This issue is coming in ios only, it is perfect in android.
this issue is also in awe demo on github.
Any solution is available on awe to solve this issue. Any help would be appreciated.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
