### ISSUE TITLE
Use augmented reality in STEREO mode with AWE

### ISSUE THREAD

**Issue by jucall** [awe-media/awe.js#66]
Hello. I tried to modify the example "marker_ar" for use it in Stereo VR mode (adding the line awe.settings.update({data:{value: 'stereo'}, where:{id: 'view_count'}}), but it didn't work. Do you know if it's possible do AR in Stereo mode with AWE?. I readed a lot of examples, but I didn't found an example with AR in Stereo mode with AWE. Greetings.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
