### ISSUE TITLE
Augmented Reality with camera active, with background black, for Hololens.

### ISSUE THREAD

**Issue by jucall** [awe-media/awe.js#67]
Hello. I want to make a web for Hololens, using Augmented Reality with camera active (for detect the marker), with background black. It's possible to do with AWE.js?. Greetings.

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
