### ISSUE TITLE
Non Mobile platform

### ISSUE THREAD

**Issue by talk2dug** [awe-media/awe.js#68]
Hi,

I have been looking over your project and I think its a good fit for my current project. 

To not make this too long of a post, I need a solution thats not mobile specific. I need this solution to run on a unix device, something like  PI. 

I was wondering about how to skip the autodetect mechanism and feed your library a video feed and canvas in a browser and of course feed it 3 axis location and orientation from sensors.

thoughts?

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
