### ISSUE TITLE
Dispose method

### ISSUE THREAD

**Issue by alexp25** [awe-media/awe.js#69]
Hello, I am looking to use the library for an Ionic 3 mobile application. I have successfully initialized the AR view with the camera and I didn't find any information on how to close the view/stream (e.g. when navigating to another page in the application). Is there a method for this, similar to awe.init?

**Comment by awe-media** [comment]
This github repos is now focused on supporting the development of apps using awe.js on the awe.media platform. You can still access our older awe.js library as the `deprecated` branch, however we no longer support that code.
