### ISSUE TITLE
Upload on npm

### ISSUE THREAD

**Issue by dheavy** [awe-media/awe.js#7]
Hello guys,

It would be great if this package was available on npm.

Keep up the good work!

**Comment by awe-media** [comment]
Hi @dheavy good question and it's well over due. @jordaofranca kindly put up a version from our old repository under awe-ar.

But here's a link to the latest version we just published https://www.npmjs.com/package/awe.js

Shout if you have any questions or suggestions.

**Comment by dheavy** [comment]
Thanks @awe-media! 

Keep up the good work, it's truly awesome what you delivered.
