### ISSUE TITLE
projection scale not working

### ISSUE THREAD

**Issue by johnyang90** [awe-media/awe.js#73]
Hi there, how could i update the scale of a projection using javascript?

**Comment by awe-media** [comment]
Hi @johnyang90 you can use the standard awe.js update API e.g.
```
var projection = awe.projections.view(projection_id);
projection.update({
  scale:{ x:2, y:2, z:2 }
});
```
Replace `projection_id` with the relevant id for your projection.

This will set the projection to 200% of it's default size in the x, y and z axes.

You can get a projection's existing scale using this type of code.

```
var x_scale = projection.scale.x;
```

If you find this is not working for you in some specific context please contact support AT awe.media and they'll be happy to help.
