### ISSUE TITLE
Always capturing from front camera in WebView - enumerateDevices() returns no label

### ISSUE THREAD

**Issue by faisalman** [awe-media/awe.js#9]
Hi @awe-media, I got into a problem when running awe.js from inside a WebView using Cordova, where the scene always capturing media from the front camera instead of rear camera. And since using this under a WebView, by default there is no confirmation popup to select which video capturing device to use like when running in the browser.

After inspecting with Chrome devtool, it seems that this behavior happened because every devices returned from `enumerateDevices()` in https://github.com/awe-media/awe.js/blob/master/js/awe-standard.js#L1434 has no label (tested on Sony Xperia M and Oppo F1), so the selected source always the first `videoinput` device, which in my case is the front-facing camera.

![chrome devtool](https://cloud.githubusercontent.com/assets/460302/20783713/36f580fe-b7c8-11e6-860f-9b7502d87e4a.png)

Any thought on this? Thanks :grin:

**Comment by awe-media** [comment]
Hi @faisalman funnily enough we were just about to push a fix for this issue...that's pushed now (see dbe16b6).

This handles the incomplete implementations of `facingMode` in the `getUserMedia` constraints the same way adapter.js handles it - but it's really a work around until `facingMode` is implemented properly.

Hope this helps and we'll close this now. But please let us know if you find any issues with this fix.
